### ISSUE TITLE
cuda rnn training failed on assert after if torch.isTensor(input)     

### ISSUE THREAD

**Issue by chroneus** [macournoyer/neuralconvo#28] opened 2016-05-31 03:08 UTC
-- Epoch 1 / 50	
	
torch/install/bin/luajit: ...o/torch/install/share/lua/5.1/rnn/SequencerCriterion.lua:42: expecting target table
stack traceback:
	[C]: in function 'assert'
	torch/install/share/lua/5.1/rnn/SequencerCriterion.lua:42: in function 'forward'
	./seq2seq.lua:74: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by macournoyer** [comment] 2016-07-05 20:45
Update nn and rnn:

```
   luarocks install nn
   luarocks install rnn
```

Duplicate of #31.

**Closed by macournoyer** 2016-07-05 20:45 UTC
