### ISSUE TITLE
Inconsistent Tensor Size

### ISSUE THREAD

**Issue by mhaidri** [macournoyer/neuralconvo#19] opened 2016-04-17 09:57 UTC
In 3 module of nn.Sequential:
...aidri/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:57: inconsistent tensor size at /home/mhaidri/torch/pkg/torch/lib/TH/generic/THTensorMath.c:547
stack traceback:
	[C]: in function 'add'
	...aidri/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:57: in function 'recursiveAdd'
	/home/mhaidri/torch/install/share/lua/5.1/rnn/LSTM.lua:192: in function '_updateGradInput'
	...ri/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:58: in function 'updateGradInput'
	/home/mhaidri/torch/install/share/lua/5.1/rnn/Sequencer.lua:79: in function 'updateGradInput'
	/home/mhaidri/torch/install/share/lua/5.1/nn/Module.lua:31: in function </home/mhaidri/torch/install/share/lua/5.1/nn/Module.lua:29>
	[C]: in function 'xpcall'
	/home/mhaidri/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/mhaidri/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./seq2seq.lua:90: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	...idri/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/mhaidri/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/mhaidri/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./seq2seq.lua:90: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	...idri/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by hitluobin** [comment] 2016-04-19 04:42
the same problem occurs to me

**Comment by suichen** [comment] 2016-04-25 06:06
I have the same problem

**Comment by suichen** [comment] 2016-04-25 06:31
someone say the issue is from the latest module of 'nn'. When you install this module these days, it will not compatible of this project and produce the error we see.

You can wait for the author to fix it, or see the commit of module 'nn'.

The bad news is luarocks doesn't do well on the version control. You cannot install the older version  simply, because the version of 'nn' is scm-1 and it is still scm-1 after minor updates

**Comment by macournoyer** [comment] 2016-05-13 18:43
Should be fixed by #25

**Closed by macournoyer** 2016-05-13 18:43 UTC
